require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/comments", type: :request do
  

  let(:valid_attributes) {
    { name: Faker::Lorem.question, body: Faker::Lorem.paragraph }
  }

  let(:invalid_attributes) {
    { name: nil, body: nil }
  }

  before(:context) do
    @note = Note.create({ title: Faker::Lorem.question, body: Faker::Lorem.paragraph })
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_note_comment_url(@note)
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      comment = @note.comments.create! valid_attributes
      get edit_note_comment_url(@note, comment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Comment" do
        expect {
          post note_comments_url(@note), params: { comment: valid_attributes }
        }.to change(@note.comments, :count).by(1)
      end

      it "redirects to the created comment" do
        post note_comments_url(@note), params: { comment: valid_attributes }
        expect(response).to redirect_to(@note)
      end
    end

    context "with invalid parameters" do
      it "does not create a new Comment" do
        expect {
          post note_comments_url(@note), params: { comment: invalid_attributes }
        }.to change(@note.comments, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post note_comments_url(@note), params: { comment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { name: Faker::Lorem.question, body: Faker::Lorem.paragraph }
      }

      it "updates the requested comment" do
        comment = @note.comments.create! valid_attributes
        patch note_comment_url(@note, comment), params: { comment: new_attributes }
        comment.reload
        expect(response).to redirect_to(@note)
      end

      it "redirects to the comment" do
        comment = @note.comments.create! valid_attributes
        patch note_comment_url(@note, comment), params: { comment: new_attributes }
        comment.reload
        expect(response).to redirect_to(@note)
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        comment = @note.comments.create! valid_attributes
        patch note_comment_url(@note, comment), params: { comment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested comment" do
      comment = @note.comments.create! valid_attributes
      expect {
        delete note_comment_url(@note,comment)
      }.to change(@note.comments, :count).by(-1)
    end

    it "redirects to the comments list" do
      comment = @note.comments.create! valid_attributes
      delete note_comment_url(@note, comment)
      expect(response).to redirect_to(@note)
    end
  end
end
